version: '3.8'
services:
  api_service:
    image: docker-demo
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - movie_db
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
  movie_db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie_db
    ports:
      - "3306:3306"